/**
 * OAuth 2.0 Client Configuration and Utilities
 * 
 * This module provides OAuth configuration management and validation
 * for optional account linking to an external storage system.
 */

import { randomBytes } from 'crypto';
import { db } from '@/db';
import { oauthTokens } from '@/db/schema';
import { eq } from 'drizzle-orm';
import type { OAuthToken } from '@/db/schema';

/**
 * OAuth configuration type containing all required credentials and endpoints
 */
export type OAuthConfig = {
  clientId: string;
  clientSecret: string;
  authorizationUrl: string;
  tokenUrl: string;
  redirectUri: string;
  scope: string;
};

/**
 * Token response from OAuth token endpoint
 */
export type TokenResponse = {
  access_token: string;
  refresh_token?: string;
  expires_in: number;
  token_type: string;
};

/**
 * Loads OAuth client credentials from environment variables.
 * 
 * Returns null if any required environment variable is missing,
 * allowing the application to gracefully handle unconfigured OAuth.
 * 
 * Required environment variables:
 * - OAUTH_CLIENT_ID: OAuth client identifier
 * - OAUTH_CLIENT_SECRET: OAuth client secret
 * - OAUTH_AUTHORIZATION_URL: Authorization endpoint URL
 * - OAUTH_TOKEN_URL: Token endpoint URL
 * - OAUTH_REDIRECT_URI: Callback URL for OAuth flow
 * 
 * @returns OAuthConfig object if all variables are present, null otherwise
 */
export function getOAuthConfig(): OAuthConfig | null {
  const clientId = process.env.OAUTH_CLIENT_ID;
  const clientSecret = process.env.OAUTH_CLIENT_SECRET;
  const authorizationUrl = process.env.OAUTH_AUTHORIZATION_URL;
  const tokenUrl = process.env.OAUTH_TOKEN_URL;
  const redirectUri = process.env.OAUTH_REDIRECT_URI;

  // Return null if any required variable is missing
  if (!clientId || !clientSecret || !authorizationUrl || !tokenUrl || !redirectUri) {
    return null;
  }

  return {
    clientId,
    clientSecret,
    authorizationUrl,
    tokenUrl,
    redirectUri,
    scope: 'training', // Fixed scope for accessing user qualification data
  };
}

/**
 * Checks if OAuth is properly configured with all required credentials.
 * 
 * This function is useful for conditionally rendering OAuth-related UI
 * elements and determining if linking functionality should be available.
 * 
 * @returns true if OAuth is configured, false otherwise
 */
export function isOAuthConfigured(): boolean {
  return getOAuthConfig() !== null;
}

/**
 * Generates a cryptographically secure state token for CSRF protection.
 * 
 * The state token is used to prevent cross-site request forgery attacks
 * during the OAuth authorization flow. It should be stored in the user's
 * session before redirecting to the authorization endpoint, then validated
 * when the callback is received.
 * 
 * Uses crypto.randomBytes to generate 32 bytes of random data, encoded
 * as a base64url string for URL safety.
 * 
 * @returns A cryptographically secure random string suitable for use as a state parameter
 */
export function generateStateToken(): string {
  return randomBytes(32).toString('base64url');
}

/**
 * Constructs the authorization URL for initiating the OAuth flow.
 * 
 * Builds a complete authorization URL with all required query parameters:
 * - client_id: OAuth client identifier
 * - redirect_uri: Callback URL where the authorization server will redirect
 * - response_type: Set to "code" for authorization code flow
 * - scope: Set to "training" to request access to user qualification data
 * - state: CSRF protection token
 * 
 * @param state - The state token for CSRF protection (generated by generateStateToken)
 * @returns Complete authorization URL to redirect the user to
 * @throws Error if OAuth is not configured
 */
export function buildAuthorizationUrl(state: string): string {
  const config = getOAuthConfig();
  if (!config) {
    throw new Error('OAuth not configured');
  }

  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: config.redirectUri,
    response_type: 'code',
    scope: config.scope,
    state,
  });

  return `${config.authorizationUrl}?${params.toString()}`;
}

/**
 * Exchanges an authorization code for access and refresh tokens.
 * 
 * Makes a POST request to the token endpoint with the authorization code
 * and client credentials. The token endpoint responds with an access token,
 * optional refresh token, and expiration time.
 * 
 * This function implements Requirements 3.3, 3.4, 3.5, and 3.7:
 * - Sends grant_type=authorization_code with client credentials (3.3)
 * - Extracts access_token, refresh_token, and expires_in from response (3.4)
 * - Handles network errors with descriptive error messages (3.5)
 * - Validates response structure and handles invalid responses (3.7)
 * 
 * @param code - The authorization code received from the authorization server
 * @returns Promise resolving to TokenResponse with access_token, refresh_token, expires_in, and token_type
 * @throws Error if OAuth is not configured
 * @throws Error if the network request fails
 * @throws Error if the token endpoint returns an error response
 * @throws Error if the response is missing required fields
 */
export async function exchangeCodeForTokens(code: string): Promise<TokenResponse> {
  const config = getOAuthConfig();
  if (!config) {
    throw new Error('OAuth not configured');
  }

  try {
    const response = await fetch(config.tokenUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        grant_type: 'authorization_code',
        code,
        redirect_uri: config.redirectUri,
        client_id: config.clientId,
        client_secret: config.clientSecret,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => 'Unknown error');
      throw new Error(`Token exchange failed: ${response.status} ${response.statusText} - ${errorText}`);
    }

    const data = await response.json();

    // Validate required fields in response
    if (!data.access_token || typeof data.access_token !== 'string') {
      throw new Error('Invalid token response: missing or invalid access_token');
    }

    if (!data.expires_in || typeof data.expires_in !== 'number') {
      throw new Error('Invalid token response: missing or invalid expires_in');
    }

    if (!data.token_type || typeof data.token_type !== 'string') {
      throw new Error('Invalid token response: missing or invalid token_type');
    }

    // refresh_token is optional
    if (data.refresh_token !== undefined && typeof data.refresh_token !== 'string') {
      throw new Error('Invalid token response: invalid refresh_token');
    }

    return {
      access_token: data.access_token,
      refresh_token: data.refresh_token,
      expires_in: data.expires_in,
      token_type: data.token_type,
    };
  } catch (error) {
    // Re-throw Error instances with their original message
    if (error instanceof Error) {
      throw error;
    }
    
    // Handle network errors or other unexpected failures
    throw new Error(`Token exchange failed: ${String(error)}`);
  }
}

/**
 * Stores OAuth tokens in the database for a user.
 * 
 * Persists access token, refresh token, and expiration timestamp after
 * successful token exchange. Uses Drizzle's onConflictDoUpdate to replace
 * existing tokens if the user already has stored tokens.
 * 
 * This function implements Requirements 4.1, 4.2, 4.3, 4.4, and 4.5:
 * - Persists access_token, refresh_token, and expiration timestamp (4.1)
 * - Associates tokens with exactly one user account via unique userId (4.2)
 * - Replaces existing tokens using onConflictDoUpdate (4.3)
 * - Records creation and update timestamps (4.4)
 * - Enforces unique constraint through schema definition (4.5)
 * 
 * @param userId - The ID of the user to store tokens for
 * @param accessToken - The access token from the token endpoint
 * @param refreshToken - The refresh token (may be null if not provided)
 * @param expiresIn - Token lifetime in seconds
 * @returns Promise that resolves when tokens are stored
 */
export async function storeTokens(
  userId: number,
  accessToken: string,
  refreshToken: string | null,
  expiresIn: number
): Promise<void> {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + expiresIn * 1000);

  await db
    .insert(oauthTokens)
    .values({
      userId,
      accessToken,
      refreshToken,
      expiresAt,
      createdAt: now,
      updatedAt: now,
    })
    .onConflictDoUpdate({
      target: oauthTokens.userId,
      set: {
        accessToken,
        refreshToken,
        expiresAt,
        updatedAt: now,
      },
    });
}

/**
 * Retrieves OAuth tokens for a user from the database.
 * 
 * Queries the oauthTokens table to find stored tokens for the specified user.
 * Returns null if the user has no linked account or tokens have been deleted.
 * 
 * This function implements Requirement 4.1:
 * - Retrieves persisted access_token, refresh_token, and expiration timestamp
 * 
 * @param userId - The ID of the user to retrieve tokens for
 * @returns Promise resolving to OAuthToken object if found, null otherwise
 */
export async function getTokensForUser(userId: number): Promise<OAuthToken | null> {
  const result = await db.query.oauthTokens.findFirst({
    where: eq(oauthTokens.userId, userId),
  });

  return result || null;
}

/**
 * Deletes OAuth tokens for a user from the database.
 * 
 * Removes all stored tokens for the specified user, effectively unlinking
 * their account from the external storage system. This is used when users
 * explicitly unlink their account or when token refresh fails.
 * 
 * This function implements Requirements 6.1 and 6.2:
 * - Deletes all stored tokens for a user (6.1)
 * - Removes the user's linked account status (6.2)
 * 
 * @param userId - The ID of the user to delete tokens for
 * @returns Promise that resolves when tokens are deleted
 */
export async function deleteTokensForUser(userId: number): Promise<void> {
  await db.delete(oauthTokens).where(eq(oauthTokens.userId, userId));
}

/**
 * Refreshes an expired access token using the refresh token.
 * 
 * Makes a POST request to the token endpoint with the refresh token
 * and client credentials. The token endpoint responds with a new access token,
 * optional new refresh token, and expiration time.
 * 
 * This function implements Requirements 5.1, 5.2, 5.3, and 5.5:
 * - Attempts to obtain a new access token using the refresh token (5.1)
 * - Sends grant_type=refresh_token with client credentials (5.2)
 * - Updates token store with new access token and expiration (5.3)
 * - Handles refresh failures with descriptive errors (5.5)
 * 
 * @param refreshToken - The refresh token to use for obtaining a new access token
 * @returns Promise resolving to TokenResponse with new access_token, optional refresh_token, expires_in, and token_type
 * @throws Error if OAuth is not configured
 * @throws Error if the network request fails
 * @throws Error if the token endpoint returns an error response
 * @throws Error if the response is missing required fields
 */
export async function refreshAccessToken(refreshToken: string): Promise<TokenResponse> {
  const config = getOAuthConfig();
  if (!config) {
    throw new Error('OAuth not configured');
  }

  try {
    const response = await fetch(config.tokenUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        grant_type: 'refresh_token',
        refresh_token: refreshToken,
        client_id: config.clientId,
        client_secret: config.clientSecret,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => 'Unknown error');
      throw new Error(`Token refresh failed: ${response.status} ${response.statusText} - ${errorText}`);
    }

    const data = await response.json();

    // Validate required fields in response
    if (!data.access_token || typeof data.access_token !== 'string') {
      throw new Error('Invalid token response: missing or invalid access_token');
    }

    if (!data.expires_in || typeof data.expires_in !== 'number') {
      throw new Error('Invalid token response: missing or invalid expires_in');
    }

    if (!data.token_type || typeof data.token_type !== 'string') {
      throw new Error('Invalid token response: missing or invalid token_type');
    }

    // refresh_token is optional in the response
    if (data.refresh_token !== undefined && typeof data.refresh_token !== 'string') {
      throw new Error('Invalid token response: invalid refresh_token');
    }

    return {
      access_token: data.access_token,
      refresh_token: data.refresh_token,
      expires_in: data.expires_in,
      token_type: data.token_type,
    };
  } catch (error) {
    // Re-throw Error instances with their original message
    if (error instanceof Error) {
      throw error;
    }
    
    // Handle network errors or other unexpected failures
    throw new Error(`Token refresh failed: ${String(error)}`);
  }
}

/**
 * Checks if an OAuth token is expired.
 * 
 * Compares the token's expiration timestamp against the current time
 * to determine if the token is still valid. Used before making API calls
 * to decide whether token refresh is needed.
 * 
 * This function implements Requirement 4.5:
 * - Checks token expiration to determine if refresh is needed
 * 
 * @param expiresAt - The expiration timestamp of the token
 * @returns true if the token is expired, false if still valid
 */
export function isTokenExpired(expiresAt: Date): boolean {
  return expiresAt < new Date();
}

/**
 * Retrieves a valid access token for a user, automatically refreshing if expired.
 *
 * This is the main function to call before making API requests to the external system.
 * It handles the complete token lifecycle:
 * 1. Retrieves stored tokens from database
 * 2. Returns token immediately if not expired
 * 3. Attempts automatic refresh if token is expired
 * 4. Updates stored tokens with new values from refresh
 * 5. Deletes tokens if refresh fails (user must re-authorize)
 *
 * This function implements Requirements 5.1, 5.3, 5.4, 5.5, and 5.6:
 * - Attempts to obtain new access token when expired (5.1)
 * - Updates token store with new access token and expiration (5.3)
 * - Updates stored refresh token if new one provided (5.4)
 * - Deletes stored tokens if refresh fails (5.5)
 * - Attempts token refresh before making API calls with expired tokens (5.6)
 *
 * @param userId - The ID of the user to get a valid access token for
 * @returns Promise resolving to a valid access token string, or null if user has no linked account or refresh failed
 */
export async function getValidAccessToken(userId: number): Promise<string | null> {
  // Retrieve stored tokens for the user
  const tokens = await getTokensForUser(userId);

  // Return null if user has no linked account
  if (!tokens) {
    return null;
  }

  // If token is not expired, return it immediately
  if (!isTokenExpired(tokens.expiresAt)) {
    return tokens.accessToken;
  }

  // Token is expired, attempt refresh
  if (!tokens.refreshToken) {
    // No refresh token available, delete invalid tokens
    await deleteTokensForUser(userId);
    return null;
  }

  try {
    // Attempt to refresh the access token
    const response = await refreshAccessToken(tokens.refreshToken);

    // Store new tokens (use new refresh token if provided, otherwise keep existing)
    await storeTokens(
      userId,
      response.access_token,
      response.refresh_token || tokens.refreshToken,
      response.expires_in
    );

    // Return the new access token
    return response.access_token;
  } catch (error) {
    // Refresh failed, delete invalid tokens
    console.error('Token refresh failed:', error);
    await deleteTokensForUser(userId);
    return null;
  }
}

